### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by David-Xian66** [NTFS2020/MSL2-Python#5]
我点选择目录 随便选了一个路径（随便选的）然后点确定 输出（点确定之后，没有文件的那个弹框出来了）：
`Traceback (most recent call last):
  File "/Users/xyj/Downloads/MSL2-Python-main/主程序.py", line 77, in set_adv
    for i in range(server_lines):#遍历server.properties，并且在内存中修改内容
UnboundLocalError: local variable 'server_lines' referenced before assignment
`

**Comment by xianyongjian080402** [comment]
Traceback (most recent call last):
  File "/Users/xyj/Downloads/MSL2-Python-main/主程序.py", line 77, in set_adv
    for i in range(server_lines):#遍历server.properties，并且在内存中修改内容
UnboundLocalError: local variable 'server_lines' referenced before assignment
